[workspace]
members = [ "undersea-lib","undersea-tui"]
resolver = "3"

[workspace.lints.clippy]
pedantic = {level = "warn", priority = -1}
cargo = {level = "warn", priority = -1}
new_without_default = "allow"
single_match = "allow"
