[package]
name = "undersea-lib"
version = "0.0.0"
edition = "2024"

[dependencies]
rss = "2.0"
reqwest = "0.12"
tokio = { version = "1.44" , features = ["rt", "rt-multi-thread", "macros"] }
chrono = "0.4"
thiserror = "2.0"
